In [41]:
!pip install pandas
!pip install yfinance
!pip install scipy
!pip install ta

Requirement already satisfied: pandas in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.22.4 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from pandas) (1.26.4)
Requirement already satisfied: pytz>=2020.1 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: yfinance in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (0.2.37)
Requirement already satisfied: pandas>=1.3.0 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from yfinance) (2.2.2)
Requirement already satisfied: frozendict>=2.3.4 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from yfinance) (2.3.5)
Requirement already satisfied: multitasking>=0.0.7 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from yfinance) (0.0.11)
Requirement already satisfied: appdirs>=1.4.4 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from yfinance) (1.4.4)
Requirement already satisfied: pytz>=2022.5 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from yfinance) (2024.1)
Requirement already satisfied: requests>=2.31 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from yfinance) (2.31.0)
Requirement already satisfied: lxml>=4.9.1 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from yfinance) (4.9.1)
Requirement already satisfied: numpy>=1.16.5 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from yfinance) (1.26.4)
Requirement already satisfied: html5lib>=1.1 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from yfinance) (1.1)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from yfinance) (4.12.3)
Requirement already satisfied: peewee>=3.16.2 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from yfinance) (3.17.1)
Requirement already satisfied: soupsieve>1.2 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: six>=1.9 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: certifi>=2017.4.17 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.31->yfinance) (2024.2.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.31->yfinance) (1.26.20)
Requirement already satisfied: idna<4,>=2.5 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: scipy in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (1.12.0)
Requirement already satisfied: numpy<1.29.0,>=1.22.4 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from scipy) (1.26.4)
Collecting ta
  Downloading ta-0.11.0.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from ta) (1.26.4)
Requirement already satisfied: pandas in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from ta) (2.2.2)
Requirement already satisfied: pytz>=2020.1 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from pandas->ta) (2024.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from pandas->ta) (2.8.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from pandas->ta) (2023.3)
Requirement already satisfied: six>=1.5 in /Users/aryamangoenka/opt/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas->ta) (1.16.0)
Building wheels for collected packages: ta
  Building wheel for ta (setup.py) ... done
  Created wheel for ta: filename=ta-0.11.0-py3-none-any.whl size=29412 sha256=b1e257bd9c0a28e352cef2402f7d9302de91c03cf69bb7ab2d54a6e8acb9f576
  Stored in directory: /Users/aryamangoenka/Library/Caches/pip/wheels/61/d8/66/8018676d483fa5edb5337a7a25ee8c029ac255be25f90f3cd5
Successfully built ta
Installing collected packages: ta
Successfully installed ta-0.11.0

In [42]:
import pandas as pd
import yfinance as yf
import numpy as np
from scipy import stats
from datetime import datetime, timedelta
import ta

In [32]:
df = pd.read_csv('nasdaq_stocks.csv')  # Ensure the file contains a 'Symbol' column
nasdaq_stocks = df.sample(n=250, random_state=None)
print(nasdaq_stocks)

     Symbol                                      Security Name
2682   MCHI                             iShares MSCI China ETF
2762   MKZR      MacKenzie Realty Capital, Inc. - Common Stock
3650   RFEU          First Trust RiverFront Dynamic Europe ETF
3809    SDA     SunCar Technology Group Inc. - Ordinary Shares
1653   FRSX  Foresight Autonomous Holdings Ltd. - American ...
...     ...                                                ...
4173   TCOM  Trip.com Group Limited - American Depositary S...
4256   TNXP  Tonix Pharmaceuticals Holding Corp. - Common S...
3348   PLAO  Patria Latin American Opportunity Acquisition ...
3169   ONMD              OneMedNet Corp - Class A Common Stock
1537    FEM         First Trust Emerging Markets AlphaDEX Fund

[250 rows x 2 columns]

In [33]:
def calculate_rs_ratings(df, symbol_column='Symbol', rs_period=252):
    """
    Calculates the Relative Strength (RS) rating of stocks relative to the S&P 500.

    Parameters:
    - df (pd.DataFrame): DataFrame containing stock symbols.
    - symbol_column (str): Name of the column containing stock symbols.
    - rs_period (int): Number of trading days to calculate RS (default is ~12 months).

    Returns:
    - pd.DataFrame: Original DataFrame with an added 'RS_Rating' column.
    """
    
    # Define the benchmark
    benchmark_symbol = '^GSPC'  # S&P 500 index symbol in Yahoo Finance

    # Calculate the start and end dates
    end_date = datetime.today()
    start_date = end_date - timedelta(days=rs_period*1.5)  # Extra days to account for weekends/holidays

    # Fetch benchmark data
    print("Fetching S&P 500 data...")
    benchmark_data = yf.download(benchmark_symbol, start=start_date, end=end_date, progress=False)
    if benchmark_data.empty:
        raise ValueError("Failed to fetch S&P 500 data.")
    benchmark_data = benchmark_data['Adj Close'].dropna()

    # Calculate benchmark returns
    benchmark_start = benchmark_data.iloc[0]
    benchmark_end = benchmark_data.iloc[-1]
    benchmark_return = (benchmark_end / benchmark_start - 1) * 100  # Percentage

    print(f"S&P 500 return over the period: {benchmark_return:.2f}%")

    # Lists to store results
    symbols = []
    rs_returns = []

    # Iterate over each symbol to calculate returns
    for symbol in df[symbol_column]:
        try:
            print(f"Fetching data for {symbol}...")
            stock_data = yf.download(symbol, start=start_date, end=end_date, progress=False)
            if stock_data.empty:
                print(f"Warning: No data fetched for {symbol}. Skipping.")
                continue
            stock_data = stock_data['Adj Close'].dropna()

            # Ensure we have enough data
            if len(stock_data) < rs_period:
                print(f"Warning: Not enough data for {symbol}. Skipping.")
                continue

            # Calculate stock returns
            stock_start = stock_data.iloc[0]
            stock_end = stock_data.iloc[-1]
            stock_return = (stock_end / stock_start - 1) * 100  # Percentage

            # Relative Strength
            rs = stock_return - benchmark_return

            symbols.append(symbol)
            rs_returns.append(rs)

            print(f"{symbol}: Stock Return = {stock_return:.2f}%, RS = {rs:.2f}%")
        
        except Exception as e:
            print(f"Error processing {symbol}: {e}")
            continue

    # Create a DataFrame for RS
    rs_df = pd.DataFrame({
        'Symbol': symbols,
        'RS': rs_returns
    })

    # Calculate RS Rating as percentile
    rs_df['RS_Rating'] = rs_df['RS'].rank(pct=True) * 100  # Percentile (0-100)

    # Merge RS_Rating back to the original DataFrame
    result_df = df.merge(rs_df[['Symbol', 'RS_Rating']], on='Symbol', how='left')

    return result_df

In [53]:
calculate_rs_ratings(nasdaq_stocks)

Fetching S&P 500 data...
S&P 500 return over the period: 32.66%
Fetching data for MCHI...
MCHI: Stock Return = 10.12%, RS = -22.53%
Fetching data for MKZR...
Warning: Not enough data for MKZR. Skipping.
Fetching data for RFEU...
RFEU: Stock Return = 5.79%, RS = -26.86%
Fetching data for SDA...
SDA: Stock Return = 60.06%, RS = 27.41%
Fetching data for FRSX...
FRSX: Stock Return = -62.81%, RS = -95.46%
Fetching data for BSRR...
BSRR: Stock Return = 74.03%, RS = 41.37%
Fetching data for HIVE...
HIVE: Stock Return = 38.31%, RS = 5.65%
Fetching data for FSV...
FSV: Stock Return = 26.27%, RS = -6.39%
Fetching data for CANC...
CANC: Stock Return = 21.04%, RS = -11.61%
Fetching data for ONMDW...
Warning: Not enough data for ONMDW. Skipping.
Fetching data for BCAN...
BCAN: Stock Return = -99.76%, RS = -132.41%
Fetching data for NXLIW...
Warning: Not enough data for NXLIW. Skipping.
Fetching data for REYN...
REYN: Stock Return = 8.05%, RS = -24.61%
Fetching data for JG...
JG: Stock Return = 271.82%, RS = 239.16%
Fetching data for IGTAR...
Warning: Not enough data for IGTAR. Skipping.
Fetching data for CMPO...
CMPO: Stock Return = 212.85%, RS = 180.19%
Fetching data for GH...
GH: Stock Return = 49.00%, RS = 16.34%
Fetching data for UHG...
UHG: Stock Return = -15.94%, RS = -48.60%
Fetching data for HOVRW...
Warning: Not enough data for HOVRW. Skipping.
Fetching data for CWCO...
CWCO: Stock Return = -20.21%, RS = -52.87%
Fetching data for GNSS...
GNSS: Stock Return = 122.35%, RS = 89.70%
Fetching data for CAKE...
CAKE: Stock Return = 59.08%, RS = 26.43%
Fetching data for MPB...
MPB: Stock Return = 54.45%, RS = 21.79%
Fetching data for ALKS...
ALKS: Stock Return = 20.02%, RS = -12.64%
Fetching data for VACH...
Warning: Not enough data for VACH. Skipping.
Fetching data for RZLT...
RZLT: Stock Return = 572.00%, RS = 539.34%
Fetching data for CLOD...
Warning: Not enough data for CLOD. Skipping.
Fetching data for IOSP...
IOSP: Stock Return = 10.72%, RS = -21.93%
Fetching data for MRM...
MRM: Stock Return = -30.53%, RS = -63.19%
Fetching data for TLF...
TLF: Stock Return = -2.85%, RS = -35.51%
Fetching data for AADI...
AADI: Stock Return = -50.74%, RS = -83.39%
Fetching data for CMCSA...
CMCSA: Stock Return = 3.61%, RS = -29.05%
Fetching data for LNZA...
LNZA: Stock Return = -69.76%, RS = -102.41%
Fetching data for SDSI...
SDSI: Stock Return = 7.60%, RS = -25.06%
Fetching data for SMBC...
SMBC: Stock Return = 47.72%, RS = 15.07%
Fetching data for ADAG...
ADAG: Stock Return = 70.44%, RS = 37.78%
Fetching data for ABCL...
ABCL: Stock Return = -34.57%, RS = -67.22%
Fetching data for VRDN...
VRDN: Stock Return = 33.11%, RS = 0.45%
Fetching data for EGAN...
EGAN: Stock Return = -29.03%, RS = -61.68%
Fetching data for NCI...
Warning: Not enough data for NCI. Skipping.
Fetching data for BSCO...
BSCO: Stock Return = 5.83%, RS = -26.82%
Fetching data for CHARR...
Warning: Not enough data for CHARR. Skipping.
Fetching data for CADL...
CADL: Stock Return = 428.65%, RS = 396.00%
Fetching data for WW...
WW: Stock Return = -81.05%, RS = -113.70%
Fetching data for NFLX...
NFLX: Stock Return = 86.91%, RS = 54.25%
Fetching data for ZWZZT...
Warning: Not enough data for ZWZZT. Skipping.
Fetching data for FMSTW...
Warning: Not enough data for FMSTW. Skipping.
Fetching data for AIHS...
AIHS: Stock Return = 250.59%, RS = 217.93%
Fetching data for VSAT...
VSAT: Stock Return = -53.19%, RS = -85.84%
Fetching data for SNEX...
SNEX: Stock Return = 72.28%, RS = 39.63%
Fetching data for TUR...
TUR: Stock Return = 4.83%, RS = -27.83%
Fetching data for GLACR...
Warning: Not enough data for GLACR. Skipping.
Fetching data for SLRC...
SLRC: Stock Return = 24.95%, RS = -7.70%
Fetching data for EYE...
EYE: Stock Return = -38.23%, RS = -70.89%
Fetching data for LSBPW...
Warning: Not enough data for LSBPW. Skipping.
Fetching data for SEIE...
Warning: Not enough data for SEIE. Skipping.
Fetching data for LFMD...
LFMD: Stock Return = -7.18%, RS = -39.84%
Fetching data for FARO...
FARO: Stock Return = 41.59%, RS = 8.93%
Fetching data for HFWA...
HFWA: Stock Return = 54.78%, RS = 22.12%
Fetching data for FTDR...
FTDR: Stock Return = 69.56%, RS = 36.90%
Fetching data for UTRE...
UTRE: Stock Return = 5.17%, RS = -27.49%
Fetching data for AITR...
Warning: Not enough data for AITR. Skipping.
Fetching data for NERD...
NERD: Stock Return = 38.62%, RS = 5.96%
Fetching data for CXAI...
CXAI: Stock Return = 10.60%, RS = -22.06%
Fetching data for CLMB...
CLMB: Stock Return = 181.53%, RS = 148.87%
Fetching data for KIDS...
KIDS: Stock Return = -18.40%, RS = -51.06%
Fetching data for RDUS...
RDUS: Stock Return = -18.75%, RS = -51.41%
Fetching data for CTKB...
CTKB: Stock Return = 7.40%, RS = -25.25%
Fetching data for EJH...
EJH: Stock Return = -99.64%, RS = -132.29%
Fetching data for SOXQ...
SOXQ: Stock Return = 30.34%, RS = -2.32%
Fetching data for LPAA...
Warning: Not enough data for LPAA. Skipping.
Fetching data for BNGO...
BNGO: Stock Return = -82.19%, RS = -114.85%
Fetching data for ERNA...
ERNA: Stock Return = -60.55%, RS = -93.21%
Fetching data for RVSNW...
Warning: Not enough data for RVSNW. Skipping.
Fetching data for ICCM...
ICCM: Stock Return = 7.63%, RS = -25.02%
Fetching data for PMVP...
PMVP: Stock Return = -34.94%, RS = -67.60%
Fetching data for WTBN...
Warning: Not enough data for WTBN. Skipping.
Fetching data for DRRX...
DRRX: Stock Return = 35.38%, RS = 2.73%
Fetching data for EHTH...
EHTH: Stock Return = -30.59%, RS = -63.25%
Fetching data for RILYT...
RILYT: Stock Return = -22.20%, RS = -54.86%
Fetching data for CRKN...
CRKN: Stock Return = -99.13%, RS = -131.79%
Fetching data for BCOW...
BCOW: Stock Return = 52.74%, RS = 20.08%
Fetching data for LPAAW...
Warning: Not enough data for LPAAW. Skipping.
Fetching data for TRUP...
TRUP: Stock Return = 100.64%, RS = 67.98%
Fetching data for XAIR...
XAIR: Stock Return = -67.61%, RS = -100.27%
Fetching data for IEI...
IEI: Stock Return = 5.81%, RS = -26.85%
Fetching data for TLTM...
Warning: Not enough data for TLTM. Skipping.
Fetching data for USRD...
Warning: Not enough data for USRD. Skipping.
Fetching data for SFM...
SFM: Stock Return = 273.41%, RS = 240.75%
Fetching data for NBIX...
NBIX: Stock Return = 15.83%, RS = -16.83%
Fetching data for HPAIW...
Warning: Not enough data for HPAIW. Skipping.
Fetching data for TURB...
TURB: Stock Return = 1.31%, RS = -31.35%
Fetching data for TREE...
TREE: Stock Return = 166.33%, RS = 133.67%
Fetching data for NSPR...
NSPR: Stock Return = 5.76%, RS = -26.90%
Fetching data for NATH...
NATH: Stock Return = 35.37%, RS = 2.71%
Fetching data for AREBW...
Warning: Not enough data for AREBW. Skipping.
Fetching data for VRAR...
VRAR: Stock Return = -43.55%, RS = -76.20%
Fetching data for ALMS...
Warning: Not enough data for ALMS. Skipping.
Fetching data for NVX...
NVX: Stock Return = -0.50%, RS = -33.16%
Fetching data for VRTX...
VRTX: Stock Return = 31.19%, RS = -1.47%
Fetching data for TCX...
TCX: Stock Return = -17.10%, RS = -49.76%
Fetching data for AMLI...
AMLI: Stock Return = -42.18%, RS = -74.84%
Fetching data for CLPS...
CLPS: Stock Return = 28.70%, RS = -3.95%
Fetching data for EUDA...
EUDA: Stock Return = 288.60%, RS = 255.94%
Fetching data for NKGN...
NKGN: Stock Return = -86.01%, RS = -118.67%
Fetching data for EWZS...
EWZS: Stock Return = -23.83%, RS = -56.49%
Fetching data for QTOP...
Warning: Not enough data for QTOP. Skipping.
Fetching data for AZPN...
AZPN: Stock Return = 34.01%, RS = 1.36%
Fetching data for AAPL...
AAPL: Stock Return = 24.57%, RS = -8.08%
Fetching data for MNRO...
MNRO: Stock Return = 1.16%, RS = -31.50%
Fetching data for EVGRW...
Warning: Not enough data for EVGRW. Skipping.
Fetching data for TPIC...
TPIC: Stock Return = -20.93%, RS = -53.59%
Fetching data for VYGR...
VYGR: Stock Return = 0.29%, RS = -32.36%
Fetching data for ASYS...
ASYS: Stock Return = -26.75%, RS = -59.41%
Fetching data for ESGLW...
Warning: Not enough data for ESGLW. Skipping.
Fetching data for PNFP...
PNFP: Stock Return = 77.27%, RS = 44.61%
Fetching data for ALGS...
ALGS: Stock Return = 42.12%, RS = 9.46%
Fetching data for ACTU...
Warning: Not enough data for ACTU. Skipping.
Fetching data for ALTY...
ALTY: Stock Return = 18.89%, RS = -13.76%
Fetching data for UBX...

UBX: Stock Return = -38.61%, RS = -71.27%
Fetching data for GLLIU...
GLLIU: Stock Return = 6.92%, RS = -25.74%
Fetching data for GOCO...
GOCO: Stock Return = -1.84%, RS = -34.50%
Fetching data for ALVO...
ALVO: Stock Return = 28.56%, RS = -4.10%
Fetching data for PPTA...
PPTA: Stock Return = 198.75%, RS = 166.09%
Fetching data for VEON...
VEON: Stock Return = 63.14%, RS = 30.49%
Fetching data for AZTA...
AZTA: Stock Return = -17.50%, RS = -50.15%
Fetching data for FPXI...
FPXI: Stock Return = 23.95%, RS = -8.71%
Fetching data for SMCX...
Warning: Not enough data for SMCX. Skipping.
Fetching data for CDROW...
Warning: Not enough data for CDROW. Skipping.
Fetching data for SANW...
SANW: Stock Return = -42.91%, RS = -75.57%
Fetching data for RUMBW...
Warning: Not enough data for RUMBW. Skipping.
Fetching data for HEPA...
HEPA: Stock Return = -78.79%, RS = -111.45%
Fetching data for INDP...
INDP: Stock Return = -49.25%, RS = -81.91%
Fetching data for HLXB...
Warning: Not enough data for HLXB. Skipping.
Fetching data for CSPI...
CSPI: Stock Return = 31.99%, RS = -0.67%
Fetching data for ASNS...
ASNS: Stock Return = 9.82%, RS = -22.83%
Fetching data for BANF...
BANF: Stock Return = 47.81%, RS = 15.16%
Fetching data for MYCK...
Warning: Not enough data for MYCK. Skipping.
Fetching data for CGEN...
CGEN: Stock Return = 144.62%, RS = 111.96%
Fetching data for FOLD...
FOLD: Stock Return = -9.60%, RS = -42.26%
Fetching data for RYTM...
RYTM: Stock Return = 86.08%, RS = 53.43%
Fetching data for BULD...
BULD: Stock Return = 7.05%, RS = -25.60%
Fetching data for PY...
PY: Stock Return = 32.18%, RS = -0.48%
Fetching data for SERV...
Warning: Not enough data for SERV. Skipping.
Fetching data for PASG...
PASG: Stock Return = 79.65%, RS = 46.99%
Fetching data for LIF...
Warning: Not enough data for LIF. Skipping.
Fetching data for ABVEW...
Warning: Not enough data for ABVEW. Skipping.
Fetching data for FBOT...
FBOT: Stock Return = 18.56%, RS = -14.09%
Fetching data for BRKL...
BRKL: Stock Return = 38.85%, RS = 6.19%
Fetching data for TCRT...
TCRT: Stock Return = -78.50%, RS = -111.16%
Fetching data for MTRX...
MTRX: Stock Return = 31.68%, RS = -0.98%
Fetching data for SRZN...
SRZN: Stock Return = 69.80%, RS = 37.14%
Fetching data for FAST...
FAST: Stock Return = 41.13%, RS = 8.48%
Fetching data for IVCAW...
Warning: Not enough data for IVCAW. Skipping.
Fetching data for BNIXR...
Warning: Not enough data for BNIXR. Skipping.
Fetching data for AIMAU...
AIMAU: Stock Return = 9.29%, RS = -23.36%
Fetching data for CDNA...
CDNA: Stock Return = 153.51%, RS = 120.86%
Fetching data for RFIL...
RFIL: Stock Return = 61.83%, RS = 29.18%
Fetching data for LIFWW...
LIFWW: Stock Return = 0.00%, RS = -32.66%
Fetching data for CBNK...
CBNK: Stock Return = 42.98%, RS = 10.33%
Fetching data for HUBCW...
Warning: Not enough data for HUBCW. Skipping.
Fetching data for NETD...
NETD: Stock Return = 4.68%, RS = -27.97%
Fetching data for SOBR...
SOBR: Stock Return = -91.41%, RS = -124.07%
Fetching data for CFSB...
CFSB: Stock Return = 7.40%, RS = -25.26%
Fetching data for TASK...
TASK: Stock Return = 17.09%, RS = -15.56%
Fetching data for CDTX...
CDTX: Stock Return = 34.91%, RS = 2.26%
Fetching data for MLTX...
MLTX: Stock Return = 27.56%, RS = -5.10%
Fetching data for AWRE...
AWRE: Stock Return = -5.33%, RS = -37.98%
Fetching data for TVGNW...
Warning: Not enough data for TVGNW. Skipping.
Fetching data for VBFC...
VBFC: Stock Return = 99.95%, RS = 67.30%
Fetching data for CTXR...
CTXR: Stock Return = -82.69%, RS = -115.34%
Fetching data for IGF...
IGF: Stock Return = 27.12%, RS = -5.54%
Fetching data for EVTV...
EVTV: Stock Return = 1.12%, RS = -31.54%
Fetching data for KRYS...
KRYS: Stock Return = 88.41%, RS = 55.76%
Fetching data for HECO...
Warning: Not enough data for HECO. Skipping.
Fetching data for SLNO...
SLNO: Stock Return = 88.52%, RS = 55.86%
Fetching data for PLRZ...
Warning: Not enough data for PLRZ. Skipping.
Fetching data for AY...
AY: Stock Return = 28.02%, RS = -4.64%
Fetching data for TGAAW...
Warning: Not enough data for TGAAW. Skipping.
Fetching data for LNZAW...
Warning: Not enough data for LNZAW. Skipping.
Fetching data for HBCP...
HBCP: Stock Return = 38.62%, RS = 5.97%
Fetching data for NCNO...
NCNO: Stock Return = 38.58%, RS = 5.92%
Fetching data for MFIC...
MFIC: Stock Return = 20.50%, RS = -12.15%
Fetching data for HOLX...
HOLX: Stock Return = 10.57%, RS = -22.09%
Fetching data for CMND...
CMND: Stock Return = -63.59%, RS = -96.24%
Fetching data for ENG...
ENG: Stock Return = -40.18%, RS = -72.83%
Fetching data for UMBF...
UMBF: Stock Return = 76.68%, RS = 44.03%
Fetching data for DVLU...
DVLU: Stock Return = 39.59%, RS = 6.94%
Fetching data for BTGD...
Warning: Not enough data for BTGD. Skipping.
Fetching data for SIEB...
SIEB: Stock Return = 50.26%, RS = 17.61%
Fetching data for XEL...
XEL: Stock Return = 25.47%, RS = -7.18%
Fetching data for RGS...
RGS: Stock Return = 229.08%, RS = 196.42%
Fetching data for OZKAP...
OZKAP: Stock Return = 23.65%, RS = -9.01%
Fetching data for ALTI...
ALTI: Stock Return = -38.63%, RS = -71.29%
Fetching data for IMMR...
IMMR: Stock Return = 40.46%, RS = 7.80%
Fetching data for TTEC...
TTEC: Stock Return = -71.79%, RS = -104.45%
Fetching data for IQQQ...
Warning: Not enough data for IQQQ. Skipping.
Fetching data for LEGH...
LEGH: Stock Return = 18.52%, RS = -14.13%
Fetching data for NAMSW...
NAMSW: Stock Return = 331.43%, RS = 298.77%
Fetching data for OMGA...
OMGA: Stock Return = -55.85%, RS = -88.51%
Fetching data for AVDL...
AVDL: Stock Return = -4.82%, RS = -37.48%
Fetching data for KXIN...
KXIN: Stock Return = -98.41%, RS = -131.06%
Fetching data for IBTF...
IBTF: Stock Return = 5.54%, RS = -27.12%
Fetching data for ATLC...
ATLC: Stock Return = 86.79%, RS = 54.13%
Fetching data for TETEW...
Warning: Not enough data for TETEW. Skipping.
Fetching data for RGTI...
RGTI: Stock Return = 190.48%, RS = 157.82%
Fetching data for INDB...
INDB: Stock Return = 33.43%, RS = 0.77%
Fetching data for GP...
GP: Stock Return = -65.72%, RS = -98.38%
Fetching data for TSVT...
TSVT: Stock Return = 129.31%, RS = 96.65%
Fetching data for ADUR...
Warning: Not enough data for ADUR. Skipping.
Fetching data for PEY...
PEY: Stock Return = 24.58%, RS = -8.08%
Fetching data for RFDI...
RFDI: Stock Return = 14.83%, RS = -17.83%
Fetching data for HRTS...
HRTS: Stock Return = 22.07%, RS = -10.59%
Fetching data for WTMAU...
WTMAU: Stock Return = 4.06%, RS = -28.59%
Fetching data for TRMD...
TRMD: Stock Return = -26.35%, RS = -59.01%
Fetching data for OABI...
OABI: Stock Return = -13.50%, RS = -46.15%
Fetching data for WGS...
WGS: Stock Return = 5539.57%, RS = 5506.91%
Fetching data for AFBI...
AFBI: Stock Return = 49.55%, RS = 16.90%
Fetching data for TIGR...
TIGR: Stock Return = 16.73%, RS = -15.92%
Fetching data for QNCX...
QNCX: Stock Return = 132.95%, RS = 100.30%
Fetching data for CSB...
CSB: Stock Return = 30.47%, RS = -2.19%
Fetching data for VFF...
VFF: Stock Return = -4.02%, RS = -36.68%
Fetching data for NTGR...
NTGR: Stock Return = 91.59%, RS = 58.93%
Fetching data for VERI...
VERI: Stock Return = 21.66%, RS = -11.00%
Fetching data for ARM...
ARM: Stock Return = 128.85%, RS = 96.20%
Fetching data for MDIV...
MDIV: Stock Return = 20.53%, RS = -12.13%
Fetching data for SUNE...
SUNE: Stock Return = -99.30%, RS = -131.95%
Fetching data for BPTH...
BPTH: Stock Return = -92.45%, RS = -125.11%
Fetching data for SLNH...
SLNH: Stock Return = -5.00%, RS = -37.66%
Fetching data for LPLA...
LPLA: Stock Return = 45.12%, RS = 12.47%
Fetching data for PXLW...
PXLW: Stock Return = -33.90%, RS = -66.55%
Fetching data for PSCE...
PSCE: Stock Return = 2.54%, RS = -30.11%
Fetching data for BLRX...
BLRX: Stock Return = -82.35%, RS = -115.01%
Fetching data for LBPH...
LBPH: Stock Return = 1286.82%, RS = 1254.16%
Fetching data for WDC...
WDC: Stock Return = 54.15%, RS = 21.49%
Fetching data for SBFG...
SBFG: Stock Return = 65.28%, RS = 32.63%
Fetching data for WSBC...
WSBC: Stock Return = 35.30%, RS = 2.65%
Fetching data for BRHY...
Warning: Not enough data for BRHY. Skipping.
Fetching data for BWBBP...
BWBBP: Stock Return = 33.51%, RS = 0.86%
Fetching data for NXTG...

NXTG: Stock Return = 20.78%, RS = -11.88%
Fetching data for AVS...
Warning: Not enough data for AVS. Skipping.
Fetching data for OPINL...
OPINL: Stock Return = 2.05%, RS = -30.61%
Fetching data for DIOD...
DIOD: Stock Return = -8.33%, RS = -40.99%
Fetching data for AVTE...
AVTE: Stock Return = -81.87%, RS = -114.53%
Fetching data for HTZWW...
Warning: Not enough data for HTZWW. Skipping.
Fetching data for TCOM...
TCOM: Stock Return = 76.30%, RS = 43.65%
Fetching data for TNXP...
TNXP: Stock Return = -98.76%, RS = -131.42%
Fetching data for PLAO...
PLAO: Stock Return = 5.34%, RS = -27.31%
Fetching data for ONMD...
ONMD: Stock Return = -80.17%, RS = -112.82%
Fetching data for FEM...
FEM: Stock Return = 8.08%, RS = -24.58%

    Symbol                                      Security Name  RS_Rating
0     MCHI                             iShares MSCI China ETF  46.231156
1     MKZR      MacKenzie Realty Capital, Inc. - Common Stock        NaN
2     RFEU          First Trust RiverFront Dynamic Europe ETF  39.698492
3      SDA     SunCar Technology Group Inc. - Ordinary Shares  79.396985
4     FRSX  Foresight Autonomous Holdings Ltd. - American ...  11.557789
..     ...                                                ...        ...
245   TCOM  Trip.com Group Limited - American Depositary S...  83.919598
246   TNXP  Tonix Pharmaceuticals Holding Corp. - Common S...   2.512563
247   PLAO  Patria Latin American Opportunity Acquisition ...  38.190955
248   ONMD              OneMedNet Corp - Class A Common Stock   7.537688
249    FEM         First Trust Emerging Markets AlphaDEX Fund  44.723618

[250 rows x 3 columns]

In [54]:
def calculate_technical_indicators_with_ta(df, symbol_column='Symbol'):
    """
    Calculates technical indicators for each stock using the 'ta' library.
    
    Indicators:
    - 50 Day Moving Average
    - 150 Day Moving Average
    - 200 Day Moving Average
    - 52 Week Low
    - 52 Week High
    """
    # Define required periods
    ma_periods = [50, 150, 200]
    weeks_52 = 252  # Approximate number of trading days in 52 weeks

    # Calculate the start date to fetch sufficient data
    end_date = datetime.today()
    start_date = end_date - timedelta(days=weeks_52 * 2)  # Buffer for non-trading days

    # Lists to store results
    symbols = []
    ma_50_list = []
    ma_150_list = []
    ma_200_list = []
    low_52w_list = []
    high_52w_list = []

    # Iterate over each symbol to calculate indicators
    for symbol in df[symbol_column]:
        try:
            print(f"Fetching data for {symbol} for technical indicators...")
            stock_data = yf.download(symbol, start=start_date, end=end_date, progress=False)
            if stock_data.empty:
                print(f"Warning: No data fetched for {symbol}. Skipping.")
                continue
            adj_close = stock_data['Adj Close'].dropna()

            # Ensure we have enough data
            if len(adj_close) < max(ma_periods + [weeks_52]):
                print(f"Warning: Not enough data for {symbol}. Skipping.")
                continue

            # Calculate Moving Averages
            ma_50 = adj_close.rolling(window=50).mean().iloc[-1]
            ma_150 = adj_close.rolling(window=150).mean().iloc[-1]
            ma_200 = adj_close.rolling(window=200).mean().iloc[-1]

            # Calculate 52 Week Low and High
            low_52w = adj_close.rolling(window=weeks_52).min().iloc[-1]
            high_52w = adj_close.rolling(window=weeks_52).max().iloc[-1]

            # Append results
            symbols.append(symbol)
            ma_50_list.append(ma_50)
            ma_150_list.append(ma_150)
            ma_200_list.append(ma_200)
            low_52w_list.append(low_52w)
            high_52w_list.append(high_52w)

            print(f"{symbol}: 50 MA = {ma_50:.2f}, 150 MA = {ma_150:.2f}, 200 MA = {ma_200:.2f}, "
                  f"52W Low = {low_52w:.2f}, 52W High = {high_52w:.2f}")

        except Exception as e:
            print(f"Error processing {symbol}: {e}")
            continue

    # Create a DataFrame for Indicators
    indicators_df = pd.DataFrame({
        'Stock': symbols,
        'SMA_50': ma_50_list,
        'SMA_150': ma_150_list,
        'SMA_200': ma_200_list,
#         '52 Week Low': low_52w_list,
#         '52 Week High': high_52w_list
    })

    return indicators_df

In [58]:
nasdaq_stocks = calculate_technical_indicators_with_ta(nasdaq_stocks)

Fetching data for MCHI for technical indicators...
MCHI: 50 MA = 49.75, 150 MA = 45.12, 200 MA = 43.75, 52W Low = 35.88, 52W High = 59.67
Fetching data for MKZR for technical indicators...
Warning: Not enough data for MKZR. Skipping.
Fetching data for RFEU for technical indicators...
RFEU: 50 MA = 64.47, 150 MA = 65.04, 200 MA = 64.59, 52W Low = 59.23, 52W High = 68.33
Fetching data for SDA for technical indicators...
SDA: 50 MA = 9.98, 150 MA = 9.22, 200 MA = 8.64, 52W Low = 6.19, 52W High = 11.41
Fetching data for FRSX for technical indicators...
FRSX: 50 MA = 0.66, 150 MA = 0.86, 200 MA = 0.92, 52W Low = 0.59, 52W High = 2.02
Fetching data for BSRR for technical indicators...
BSRR: 50 MA = 29.55, 150 MA = 26.18, 200 MA = 24.20, 52W Low = 17.22, 52W High = 34.59
Fetching data for HIVE for technical indicators...
HIVE: 50 MA = 3.74, 150 MA = 3.27, 200 MA = 3.28, 52W Low = 2.27, 52W High = 5.72
Fetching data for FSV for technical indicators...
FSV: 50 MA = 186.02, 150 MA = 169.46, 200 MA = 167.33, 52W Low = 141.40, 52W High = 197.05
Fetching data for CANC for technical indicators...
CANC: 50 MA = 27.89, 150 MA = 28.05, 200 MA = 27.86, 52W Low = 23.89, 52W High = 29.96
Fetching data for ONMDW for technical indicators...
Warning: Not enough data for ONMDW. Skipping.
Fetching data for BCAN for technical indicators...
BCAN: 50 MA = 8.05, 150 MA = 10.37, 200 MA = 61.11, 52W Low = 8.00, 52W High = 2907.00
Fetching data for NXLIW for technical indicators...
Warning: Not enough data for NXLIW. Skipping.
Fetching data for REYN for technical indicators...
REYN: 50 MA = 28.86, 150 MA = 28.69, 200 MA = 28.53, 52W Low = 25.41, 52W High = 32.23
Fetching data for JG for technical indicators...
JG: 50 MA = 6.58, 150 MA = 4.35, 200 MA = 4.03, 52W Low = 1.90, 52W High = 9.40
Fetching data for IGTAR for technical indicators...
Warning: Not enough data for IGTAR. Skipping.
Fetching data for CMPO for technical indicators...
CMPO: 50 MA = 14.69, 150 MA = 10.47, 200 MA = 9.31, 52W Low = 4.49, 52W High = 16.19
Fetching data for GH for technical indicators...
GH: 50 MA = 25.01, 150 MA = 26.71, 200 MA = 24.72, 52W Low = 16.07, 52W High = 36.29
Fetching data for UHG for technical indicators...
UHG: 50 MA = 5.95, 150 MA = 5.99, 200 MA = 6.20, 52W Low = 5.17, 52W High = 8.92
Fetching data for HOVRW for technical indicators...
Warning: Not enough data for HOVRW. Skipping.
Fetching data for CWCO for technical indicators...
CWCO: 50 MA = 25.31, 150 MA = 26.19, 200 MA = 26.48, 52W Low = 23.65, 52W High = 37.14
Fetching data for GNSS for technical indicators...
GNSS: 50 MA = 3.73, 150 MA = 2.86, 200 MA = 2.66, 52W Low = 1.54, 52W High = 4.00
Fetching data for CAKE for technical indicators...
CAKE: 50 MA = 43.63, 150 MA = 39.53, 200 MA = 38.28, 52W Low = 30.49, 52W High = 50.64
Fetching data for MPB for technical indicators...
MPB: 50 MA = 30.81, 150 MA = 26.40, 200 MA = 24.76, 52W Low = 18.76, 52W High = 33.02
Fetching data for ALKS for technical indicators...
ALKS: 50 MA = 27.99, 150 MA = 26.37, 200 MA = 26.63, 52W Low = 23.01, 52W High = 32.56
Fetching data for VACH for technical indicators...
Warning: Not enough data for VACH. Skipping.
Fetching data for RZLT for technical indicators...
RZLT: 50 MA = 5.13, 150 MA = 4.51, 200 MA = 3.93, 52W Low = 0.77, 52W High = 5.96
Fetching data for CLOD for technical indicators...
Warning: Not enough data for CLOD. Skipping.
Fetching data for IOSP for technical indicators...
IOSP: 50 MA = 113.77, 150 MA = 117.91, 200 MA = 119.10, 52W Low = 103.76, 52W High = 130.53
Fetching data for MRM for technical indicators...
MRM: 50 MA = 2.96, 150 MA = 3.93, 200 MA = 4.45, 52W Low = 2.32, 52W High = 6.30
Fetching data for TLF for technical indicators...
TLF: 50 MA = 4.23, 150 MA = 4.34, 200 MA = 4.40, 52W Low = 3.96, 52W High = 4.97
Fetching data for AADI for technical indicators...
AADI: 50 MA = 2.07, 150 MA = 1.80, 200 MA = 1.86, 52W Low = 1.32, 52W High = 5.37
Fetching data for CMCSA for technical indicators...
CMCSA: 50 MA = 42.19, 150 MA = 39.79, 200 MA = 40.02, 52W Low = 36.33, 52W High = 45.67
Fetching data for LNZA for technical indicators...
LNZA: 50 MA = 1.64, 150 MA = 1.85, 200 MA = 2.16, 52W Low = 1.00, 52W High = 5.41
Fetching data for SDSI for technical indicators...
SDSI: 50 MA = 51.19, 150 MA = 50.49, 200 MA = 50.11, 52W Low = 47.95, 52W High = 51.50
Fetching data for SMBC for technical indicators...
SMBC: 50 MA = 60.12, 150 MA = 51.54, 200 MA = 49.09, 52W Low = 39.55, 52W High = 67.05
Fetching data for ADAG for technical indicators...
ADAG: 50 MA = 2.48, 150 MA = 2.60, 200 MA = 2.67, 52W Low = 1.47, 52W High = 4.15
Fetching data for ABCL for technical indicators...
ABCL: 50 MA = 2.70, 150 MA = 3.00, 200 MA = 3.39, 52W Low = 2.39, 52W High = 5.97
Fetching data for VRDN for technical indicators...
VRDN: 50 MA = 22.73, 150 MA = 17.28, 200 MA = 17.26, 52W Low = 11.60, 52W High = 25.71
Fetching data for EGAN for technical indicators...
EGAN: 50 MA = 5.12, 150 MA = 5.98, 200 MA = 6.04, 52W Low = 4.79, 52W High = 8.46
Fetching data for NCI for technical indicators...
Warning: Not enough data for NCI. Skipping.
Fetching data for BSCO for technical indicators...
BSCO: 50 MA = 21.02, 150 MA = 20.81, 200 MA = 20.70, 52W Low = 20.02, 52W High = 21.13
Fetching data for CHARR for technical indicators...
Warning: Not enough data for CHARR. Skipping.
Fetching data for CADL for technical indicators...
CADL: 50 MA = 5.60, 150 MA = 6.63, 200 MA = 5.75, 52W Low = 0.78, 52W High = 14.00
Fetching data for WW for technical indicators...
WW: 50 MA = 1.08, 150 MA = 1.20, 200 MA = 1.50, 52W Low = 0.69, 52W High = 9.59
Fetching data for NFLX for technical indicators...
NFLX: 50 MA = 769.51, 150 MA = 690.66, 200 MA = 669.06, 52W Low = 446.73, 52W High = 897.79
Fetching data for ZWZZT for technical indicators...
Warning: Not enough data for ZWZZT. Skipping.
Fetching data for FMSTW for technical indicators...
Warning: Not enough data for FMSTW. Skipping.
Fetching data for AIHS for technical indicators...
AIHS: 50 MA = 0.97, 150 MA = 0.97, 200 MA = 0.95, 52W Low = 0.31, 52W High = 1.45
Fetching data for VSAT for technical indicators...
VSAT: 50 MA = 10.21, 150 MA = 14.23, 200 MA = 15.09, 52W Low = 6.83, 52W High = 28.25
Fetching data for SNEX for technical indicators...
SNEX: 50 MA = 90.58, 150 MA = 81.54, 200 MA = 78.11, 52W Low = 61.13, 52W High = 104.56
Fetching data for TUR for technical indicators...
TUR: 50 MA = 34.63, 150 MA = 38.47, 200 MA = 38.03, 52W Low = 31.23, 52W High = 44.04
Fetching data for GLACR for technical indicators...
Warning: Not enough data for GLACR. Skipping.
Fetching data for SLRC for technical indicators...
SLRC: 50 MA = 15.53, 150 MA = 15.38, 200 MA = 15.10, 52W Low = 13.63, 52W High = 16.75
Fetching data for EYE for technical indicators...
EYE: 50 MA = 10.80, 150 MA = 12.36, 200 MA = 14.55, 52W Low = 9.68, 52W High = 23.81
Fetching data for LSBPW for technical indicators...
Warning: Not enough data for LSBPW. Skipping.
Fetching data for SEIE for technical indicators...
Warning: Not enough data for SEIE. Skipping.
Fetching data for LFMD for technical indicators...
LFMD: 50 MA = 5.13, 150 MA = 6.41, 200 MA = 7.15, 52W Low = 4.08, 52W High = 12.51
Fetching data for FARO for technical indicators...
FARO: 50 MA = 20.78, 150 MA = 18.43, 200 MA = 19.00, 52W Low = 14.17, 52W High = 27.98
Fetching data for HFWA for technical indicators...
HFWA: 50 MA = 23.33, 150 MA = 20.78, 200 MA = 20.02, 52W Low = 16.34, 52W High = 27.28
Fetching data for FTDR for technical indicators...
FTDR: 50 MA = 52.12, 150 MA = 43.70, 200 MA = 40.60, 52W Low = 29.59, 52W High = 59.54
Fetching data for UTRE for technical indicators...
UTRE: 50 MA = 49.24, 150 MA = 48.71, 200 MA = 48.41, 52W Low = 47.09, 52W High = 49.80
Fetching data for AITR for technical indicators...
Warning: Not enough data for AITR. Skipping.
Fetching data for NERD for technical indicators...
NERD: 50 MA = 18.36, 150 MA = 16.82, 200 MA = 16.43, 52W Low = 14.38, 52W High = 20.61
Fetching data for CXAI for technical indicators...
CXAI: 50 MA = 1.54, 150 MA = 2.13, 200 MA = 2.36, 52W Low = 1.04, 52W High = 6.15
Fetching data for CLMB for technical indicators...
CLMB: 50 MA = 111.02, 150 MA = 82.89, 200 MA = 78.69, 52W Low = 47.26, 52W High = 139.88
Fetching data for KIDS for technical indicators...
KIDS: 50 MA = 26.10, 150 MA = 29.29, 200 MA = 29.06, 52W Low = 22.69, 52W High = 35.39
Fetching data for RDUS for technical indicators...

RDUS: 50 MA = 18.07, 150 MA = 16.66, 200 MA = 17.34, 52W Low = 13.54, 52W High = 30.43
Fetching data for CTKB for technical indicators...
CTKB: 50 MA = 5.62, 150 MA = 5.75, 200 MA = 6.06, 52W Low = 4.69, 52W High = 9.51
Fetching data for EJH for technical indicators...
EJH: 50 MA = 0.92, 150 MA = 5.12, 200 MA = 8.53, 52W Low = 0.71, 52W High = 219.00
Fetching data for SOXQ for technical indicators...
SOXQ: 50 MA = 40.29, 150 MA = 40.36, 200 MA = 39.60, 52W Low = 28.57, 52W High = 46.46
Fetching data for LPAA for technical indicators...
Warning: Not enough data for LPAA. Skipping.
Fetching data for BNGO for technical indicators...
BNGO: 50 MA = 0.33, 150 MA = 0.57, 200 MA = 0.69, 52W Low = 0.21, 52W High = 2.10
Fetching data for ERNA for technical indicators...
ERNA: 50 MA = 0.96, 150 MA = 1.55, 200 MA = 1.68, 52W Low = 0.43, 52W High = 2.47
Fetching data for RVSNW for technical indicators...
Warning: Not enough data for RVSNW. Skipping.
Fetching data for ICCM for technical indicators...
ICCM: 50 MA = 0.65, 150 MA = 0.75, 200 MA = 0.88, 52W Low = 0.53, 52W High = 1.48
Fetching data for PMVP for technical indicators...
PMVP: 50 MA = 1.58, 150 MA = 1.65, 200 MA = 1.66, 52W Low = 1.44, 52W High = 3.26
Fetching data for WTBN for technical indicators...
Warning: Not enough data for WTBN. Skipping.
Fetching data for DRRX for technical indicators...
DRRX: 50 MA = 1.25, 150 MA = 1.34, 200 MA = 1.26, 52W Low = 0.50, 52W High = 1.78
Fetching data for EHTH for technical indicators...
EHTH: 50 MA = 4.76, 150 MA = 4.70, 200 MA = 4.96, 52W Low = 3.60, 52W High = 9.37
Fetching data for RILYT for technical indicators...
RILYT: 50 MA = 9.89, 150 MA = 13.22, 200 MA = 13.40, 52W Low = 6.91, 52W High = 17.99
Fetching data for CRKN for technical indicators...
CRKN: 50 MA = 1.03, 150 MA = 4.63, 200 MA = 6.07, 52W Low = 0.28, 52W High = 36.00
Fetching data for BCOW for technical indicators...
BCOW: 50 MA = 9.95, 150 MA = 8.76, 200 MA = 8.33, 52W Low = 6.20, 52W High = 10.14
Fetching data for LPAAW for technical indicators...
Warning: Not enough data for LPAAW. Skipping.
Fetching data for TRUP for technical indicators...
TRUP: 50 MA = 49.72, 150 MA = 39.15, 200 MA = 35.82, 52W Low = 19.85, 52W High = 55.48
Fetching data for XAIR for technical indicators...
XAIR: 50 MA = 0.43, 150 MA = 0.67, 200 MA = 0.91, 52W Low = 0.30, 52W High = 2.17
Fetching data for IEI for technical indicators...
IEI: 50 MA = 117.18, 150 MA = 115.95, 200 MA = 115.13, 52W Low = 111.34, 52W High = 119.58
Fetching data for TLTM for technical indicators...
Warning: Not enough data for TLTM. Skipping.
Fetching data for USRD for technical indicators...
Warning: Not enough data for USRD. Skipping.
Fetching data for SFM for technical indicators...
SFM: 50 MA = 126.26, 150 MA = 99.79, 200 MA = 90.41, 52W Low = 43.08, 52W High = 154.48
Fetching data for NBIX for technical indicators...
NBIX: 50 MA = 119.09, 150 MA = 132.17, 200 MA = 133.27, 52W Low = 111.62, 52W High = 153.15
Fetching data for HPAIW for technical indicators...
Warning: Not enough data for HPAIW. Skipping.
Fetching data for TURB for technical indicators...
TURB: 50 MA = 1.58, 150 MA = 1.35, 200 MA = 1.31, 52W Low = 0.87, 52W High = 3.03
Fetching data for TREE for technical indicators...
TREE: 50 MA = 52.67, 150 MA = 49.60, 200 MA = 46.76, 52W Low = 17.70, 52W High = 61.99
Fetching data for NSPR for technical indicators...
NSPR: 50 MA = 2.59, 150 MA = 2.59, 200 MA = 2.54, 52W Low = 1.85, 52W High = 3.39
Fetching data for NATH for technical indicators...
NATH: 50 MA = 83.95, 150 MA = 74.97, 200 MA = 72.90, 52W Low = 63.10, 52W High = 93.04
Fetching data for AREBW for technical indicators...
Warning: Not enough data for AREBW. Skipping.
Fetching data for VRAR for technical indicators...
VRAR: 50 MA = 0.69, 150 MA = 0.89, 200 MA = 0.99, 52W Low = 0.58, 52W High = 1.65
Fetching data for ALMS for technical indicators...
Warning: Not enough data for ALMS. Skipping.
Fetching data for NVX for technical indicators...
NVX: 50 MA = 2.00, 150 MA = 1.90, 200 MA = 2.03, 52W Low = 1.42, 52W High = 3.10
Fetching data for VRTX for technical indicators...
VRTX: 50 MA = 472.90, 150 MA = 469.78, 200 MA = 455.28, 52W Low = 350.15, 52W High = 516.74
Fetching data for TCX for technical indicators...
TCX: 50 MA = 18.56, 150 MA = 20.20, 200 MA = 19.79, 52W Low = 15.75, 52W High = 27.95
Fetching data for AMLI for technical indicators...
AMLI: 50 MA = 0.70, 150 MA = 0.59, 200 MA = 0.61, 52W Low = 0.33, 52W High = 1.27
Fetching data for CLPS for technical indicators...
CLPS: 50 MA = 1.23, 150 MA = 1.00, 200 MA = 0.98, 52W Low = 0.68, 52W High = 1.44
Fetching data for EUDA for technical indicators...
EUDA: 50 MA = 4.18, 150 MA = 3.60, 200 MA = 3.10, 52W Low = 1.06, 52W High = 4.94
Fetching data for NKGN for technical indicators...
NKGN: 50 MA = 0.34, 150 MA = 0.87, 200 MA = 1.03, 52W Low = 0.23, 52W High = 3.77
Fetching data for EWZS for technical indicators...
EWZS: 50 MA = 11.98, 150 MA = 12.41, 200 MA = 12.74, 52W Low = 10.68, 52W High = 15.02
Fetching data for QTOP for technical indicators...
Warning: Not enough data for QTOP. Skipping.
Fetching data for AZPN for technical indicators...
AZPN: 50 MA = 240.12, 150 MA = 217.68, 200 MA = 213.15, 52W Low = 172.90, 52W High = 250.94
Fetching data for AAPL for technical indicators...
AAPL: 50 MA = 228.71, 150 MA = 216.33, 200 MA = 205.41, 52W Low = 164.41, 52W High = 237.33
Fetching data for MNRO for technical indicators...
MNRO: 50 MA = 28.03, 150 MA = 26.08, 200 MA = 27.08, 52W Low = 20.91, 52W High = 32.56
Fetching data for EVGRW for technical indicators...
Warning: Not enough data for EVGRW. Skipping.
Fetching data for TPIC for technical indicators...
TPIC: 50 MA = 3.49, 150 MA = 3.96, 200 MA = 3.67, 52W Low = 1.95, 52W High = 5.71
Fetching data for VYGR for technical indicators...
VYGR: 50 MA = 6.52, 150 MA = 7.39, 200 MA = 7.73, 52W Low = 5.27, 52W High = 10.84
Fetching data for ASYS for technical indicators...
ASYS: 50 MA = 5.75, 150 MA = 5.84, 200 MA = 5.61, 52W Low = 3.44, 52W High = 7.74
Fetching data for ESGLW for technical indicators...
Warning: Not enough data for ESGLW. Skipping.
Fetching data for PNFP for technical indicators...
PNFP: 50 MA = 108.27, 150 MA = 93.29, 200 MA = 90.36, 52W Low = 71.86, 52W High = 129.87
Fetching data for ALGS for technical indicators...
ALGS: 50 MA = 11.55, 150 MA = 13.10, 200 MA = 15.48, 52W Low = 6.89, 52W High = 28.25
Fetching data for ACTU for technical indicators...
Warning: Not enough data for ACTU. Skipping.
Fetching data for ALTY for technical indicators...
ALTY: 50 MA = 11.91, 150 MA = 11.44, 200 MA = 11.29, 52W Low = 10.27, 52W High = 12.13
Fetching data for UBX for technical indicators...
UBX: 50 MA = 1.34, 150 MA = 1.44, 200 MA = 1.48, 52W Low = 1.14, 52W High = 1.99
Fetching data for GLLIU for technical indicators...
GLLIU: 50 MA = 11.51, 150 MA = 11.91, 200 MA = 11.71, 52W Low = 10.80, 52W High = 15.49
Fetching data for GOCO for technical indicators...
GOCO: 50 MA = 10.85, 150 MA = 10.29, 200 MA = 10.55, 52W Low = 7.42, 52W High = 16.21
Fetching data for ALVO for technical indicators...
ALVO: 50 MA = 12.31, 150 MA = 12.46, 200 MA = 12.89, 52W Low = 9.12, 52W High = 17.27
Fetching data for PPTA for technical indicators...
PPTA: 50 MA = 9.59, 150 MA = 7.66, 200 MA = 6.86, 52W Low = 2.74, 52W High = 10.69
Fetching data for VEON for technical indicators...
VEON: 50 MA = 31.33, 150 MA = 28.16, 200 MA = 27.17, 52W Low = 18.71, 52W High = 33.95
Fetching data for AZTA for technical indicators...
AZTA: 50 MA = 45.00, 150 MA = 50.08, 200 MA = 52.43, 52W Low = 40.37, 52W High = 67.51
Fetching data for FPXI for technical indicators...
FPXI: 50 MA = 48.80, 150 MA = 47.56, 200 MA = 47.04, 52W Low = 40.46, 52W High = 50.26
Fetching data for SMCX for technical indicators...
Warning: Not enough data for SMCX. Skipping.
Fetching data for CDROW for technical indicators...
Warning: Not enough data for CDROW. Skipping.
Fetching data for SANW for technical indicators...
SANW: 50 MA = 3.78, 150 MA = 5.33, 200 MA = 6.26, 52W Low = 2.17, 52W High = 13.30
Fetching data for RUMBW for technical indicators...
Warning: Not enough data for RUMBW. Skipping.
Fetching data for HEPA for technical indicators...
HEPA: 50 MA = 0.66, 150 MA = 0.87, 200 MA = 1.22, 52W Low = 0.57, 52W High = 3.99
Fetching data for INDP for technical indicators...

INDP: 50 MA = 1.23, 150 MA = 1.77, 200 MA = 1.88, 52W Low = 1.00, 52W High = 2.80
Fetching data for HLXB for technical indicators...
Warning: Not enough data for HLXB. Skipping.
Fetching data for CSPI for technical indicators...
CSPI: 50 MA = 13.22, 150 MA = 13.82, 200 MA = 15.13, 52W Low = 8.29, 52W High = 27.84
Fetching data for ASNS for technical indicators...
ASNS: 50 MA = 1.36, 150 MA = 1.34, 200 MA = 1.25, 52W Low = 0.44, 52W High = 3.72
Fetching data for BANF for technical indicators...
BANF: 50 MA = 112.94, 150 MA = 100.68, 200 MA = 96.93, 52W Low = 80.51, 52W High = 128.09
Fetching data for MYCK for technical indicators...
Warning: Not enough data for MYCK. Skipping.
Fetching data for CGEN for technical indicators...
CGEN: 50 MA = 1.67, 150 MA = 1.84, 200 MA = 1.99, 52W Low = 0.66, 52W High = 2.95
Fetching data for FOLD for technical indicators...
FOLD: 50 MA = 10.73, 150 MA = 10.56, 200 MA = 10.90, 52W Low = 9.04, 52W High = 14.52
Fetching data for RYTM for technical indicators...
RYTM: 50 MA = 54.05, 150 MA = 47.46, 200 MA = 46.03, 52W Low = 33.43, 52W High = 67.33
Fetching data for BULD for technical indicators...
BULD: 50 MA = 21.46, 150 MA = 21.76, 200 MA = 22.12, 52W Low = 19.60, 52W High = 24.39
Fetching data for PY for technical indicators...
PY: 50 MA = 50.36, 150 MA = 47.60, 200 MA = 46.83, 52W Low = 40.24, 52W High = 52.48
Fetching data for SERV for technical indicators...
Warning: Not enough data for SERV. Skipping.
Fetching data for PASG for technical indicators...
PASG: 50 MA = 0.62, 150 MA = 0.86, 200 MA = 0.99, 52W Low = 0.47, 52W High = 1.73
Fetching data for LIF for technical indicators...
Warning: Not enough data for LIF. Skipping.
Fetching data for ABVEW for technical indicators...
Warning: Not enough data for ABVEW. Skipping.
Fetching data for FBOT for technical indicators...
FBOT: 50 MA = 27.16, 150 MA = 26.33, 200 MA = 26.20, 52W Low = 23.30, 52W High = 28.01
Fetching data for BRKL for technical indicators...
BRKL: 50 MA = 11.03, 150 MA = 9.71, 200 MA = 9.57, 52W Low = 7.95, 52W High = 12.76
Fetching data for TCRT for technical indicators...
TCRT: 50 MA = 2.44, 150 MA = 5.24, 200 MA = 8.19, 52W Low = 1.98, 52W High = 28.50
Fetching data for MTRX for technical indicators...
MTRX: 50 MA = 11.97, 150 MA = 10.86, 200 MA = 11.26, 52W Low = 8.77, 52W High = 13.45
Fetching data for SRZN for technical indicators...
SRZN: 50 MA = 10.33, 150 MA = 9.74, 200 MA = 10.30, 52W Low = 6.55, 52W High = 15.71
Fetching data for FAST for technical indicators...
FAST: 50 MA = 77.12, 150 MA = 69.69, 200 MA = 70.29, 52W Low = 58.28, 52W High = 84.35
Fetching data for IVCAW for technical indicators...
Warning: Not enough data for IVCAW. Skipping.
Fetching data for BNIXR for technical indicators...
Warning: Not enough data for BNIXR. Skipping.
Fetching data for AIMAU for technical indicators...
AIMAU: 50 MA = 11.64, 150 MA = 11.47, 200 MA = 11.40, 52W Low = 10.87, 52W High = 12.58
Fetching data for CDNA for technical indicators...
CDNA: 50 MA = 25.65, 150 MA = 21.70, 200 MA = 18.66, 52W Low = 7.56, 52W High = 33.99
Fetching data for RFIL for technical indicators...
RFIL: 50 MA = 4.03, 150 MA = 3.71, 200 MA = 3.56, 52W Low = 2.61, 52W High = 4.44
Fetching data for LIFWW for technical indicators...
LIFWW: 50 MA = 0.06, 150 MA = 0.06, 200 MA = 0.06, 52W Low = 0.06, 52W High = 0.06
Fetching data for CBNK for technical indicators...
CBNK: 50 MA = 26.13, 150 MA = 23.47, 200 MA = 22.59, 52W Low = 18.97, 52W High = 29.39
Fetching data for HUBCW for technical indicators...
Warning: Not enough data for HUBCW. Skipping.
Fetching data for NETD for technical indicators...
NETD: 50 MA = 10.68, 150 MA = 10.61, 200 MA = 10.57, 52W Low = 10.29, 52W High = 10.74
Fetching data for SOBR for technical indicators...
SOBR: 50 MA = 6.59, 150 MA = 15.51, 200 MA = 24.06, 52W Low = 3.80, 52W High = 84.70
Fetching data for CFSB for technical indicators...
CFSB: 50 MA = 6.76, 150 MA = 6.69, 200 MA = 6.86, 52W Low = 5.91, 52W High = 7.95
Fetching data for TASK for technical indicators...
TASK: 50 MA = 13.23, 150 MA = 13.78, 200 MA = 13.31, 52W Low = 10.67, 52W High = 18.94
Fetching data for CDTX for technical indicators...
CDTX: 50 MA = 12.93, 150 MA = 12.48, 200 MA = 13.17, 52W Low = 10.17, 52W High = 23.20
Fetching data for MLTX for technical indicators...
MLTX: 50 MA = 50.27, 150 MA = 46.17, 200 MA = 46.64, 52W Low = 38.43, 52W High = 63.86
Fetching data for AWRE for technical indicators...
AWRE: 50 MA = 1.78, 150 MA = 1.95, 200 MA = 1.91, 52W Low = 1.37, 52W High = 2.80
Fetching data for TVGNW for technical indicators...
Warning: Not enough data for TVGNW. Skipping.
Fetching data for VBFC for technical indicators...
VBFC: 50 MA = 75.63, 150 MA = 56.16, 200 MA = 52.37, 52W Low = 35.56, 52W High = 77.80
Fetching data for CTXR for technical indicators...
CTXR: 50 MA = 9.14, 150 MA = 14.34, 200 MA = 15.71, 52W Low = 3.32, 52W High = 25.75
Fetching data for IGF for technical indicators...
IGF: 50 MA = 54.39, 150 MA = 51.35, 200 MA = 49.94, 52W Low = 43.36, 52W High = 55.70
Fetching data for EVTV for technical indicators...
EVTV: 50 MA = 1.77, 150 MA = 1.77, 200 MA = 1.95, 52W Low = 1.09, 52W High = 2.92
Fetching data for KRYS for technical indicators...
KRYS: 50 MA = 180.24, 150 MA = 181.78, 200 MA = 177.09, 52W Low = 102.44, 52W High = 213.66
Fetching data for HECO for technical indicators...
Warning: Not enough data for HECO. Skipping.
Fetching data for SLNO for technical indicators...
SLNO: 50 MA = 53.42, 150 MA = 48.50, 200 MA = 47.17, 52W Low = 28.94, 52W High = 59.18
Fetching data for PLRZ for technical indicators...
Warning: Not enough data for PLRZ. Skipping.
Fetching data for AY for technical indicators...
AY: 50 MA = 21.81, 150 MA = 21.50, 200 MA = 20.44, 52W Low = 16.17, 52W High = 22.27
Fetching data for TGAAW for technical indicators...
Warning: Not enough data for TGAAW. Skipping.
Fetching data for LNZAW for technical indicators...
Warning: Not enough data for LNZAW. Skipping.
Fetching data for HBCP for technical indicators...
HBCP: 50 MA = 46.17, 150 MA = 41.65, 200 MA = 40.06, 52W Low = 32.99, 52W High = 51.55
Fetching data for NCNO for technical indicators...
NCNO: 50 MA = 36.67, 150 MA = 33.15, 200 MA = 32.61, 52W Low = 27.63, 52W High = 42.64
Fetching data for MFIC for technical indicators...
MFIC: 50 MA = 13.51, 150 MA = 13.91, 200 MA = 13.85, 52W Low = 11.94, 52W High = 15.18
Fetching data for HOLX for technical indicators...
HOLX: 50 MA = 80.22, 150 MA = 78.35, 200 MA = 77.75, 52W Low = 68.37, 52W High = 83.72
Fetching data for CMND for technical indicators...
CMND: 50 MA = 1.37, 150 MA = 1.36, 200 MA = 1.35, 52W Low = 0.99, 52W High = 4.37
Fetching data for ENG for technical indicators...
ENG: 50 MA = 1.34, 150 MA = 1.46, 200 MA = 1.53, 52W Low = 1.18, 52W High = 2.23
Fetching data for UMBF for technical indicators...
UMBF: 50 MA = 112.42, 150 MA = 97.34, 200 MA = 93.26, 52W Low = 70.35, 52W High = 127.60
Fetching data for DVLU for technical indicators...
DVLU: 50 MA = 31.34, 150 MA = 29.72, 200 MA = 29.37, 52W Low = 23.61, 52W High = 32.94
Fetching data for BTGD for technical indicators...
Warning: Not enough data for BTGD. Skipping.
Fetching data for SIEB for technical indicators...
SIEB: 50 MA = 2.52, 150 MA = 2.10, 200 MA = 2.06, 52W Low = 1.47, 52W High = 2.93
Fetching data for XEL for technical indicators...
XEL: 50 MA = 66.06, 150 MA = 59.55, 200 MA = 57.83, 52W Low = 47.03, 52W High = 72.92
Fetching data for RGS for technical indicators...
RGS: 50 MA = 23.73, 150 MA = 18.72, 200 MA = 15.96, 52W Low = 4.15, 52W High = 34.50
Fetching data for OZKAP for technical indicators...
OZKAP: 50 MA = 18.17, 150 MA = 16.90, 200 MA = 16.69, 52W Low = 14.24, 52W High = 19.48
Fetching data for ALTI for technical indicators...
ALTI: 50 MA = 4.12, 150 MA = 4.40, 200 MA = 4.69, 52W Low = 3.50, 52W High = 9.07
Fetching data for IMMR for technical indicators...
IMMR: 50 MA = 8.60, 150 MA = 9.42, 200 MA = 8.85, 52W Low = 6.30, 52W High = 13.44
Fetching data for TTEC for technical indicators...
TTEC: 50 MA = 5.17, 150 MA = 5.80, 200 MA = 7.20, 52W Low = 3.85, 52W High = 22.24
Fetching data for IQQQ for technical indicators...
Warning: Not enough data for IQQQ. Skipping.
Fetching data for LEGH for technical indicators...
LEGH: 50 MA = 26.37, 150 MA = 25.23, 200 MA = 24.54, 52W Low = 19.59, 52W High = 28.86
Fetching data for NAMSW for technical indicators...
NAMSW: 50 MA = 9.34, 150 MA = 8.69, 200 MA = 9.12, 52W Low = 2.10, 52W High = 13.85
Fetching data for OMGA for technical indicators...

OMGA: 50 MA = 1.08, 150 MA = 1.61, 200 MA = 2.05, 52W Low = 0.76, 52W High = 5.32
Fetching data for AVDL for technical indicators...
AVDL: 50 MA = 12.99, 150 MA = 14.80, 200 MA = 15.07, 52W Low = 10.72, 52W High = 18.82
Fetching data for KXIN for technical indicators...
KXIN: 50 MA = 6.97, 150 MA = 7.14, 200 MA = 8.29, 52W Low = 1.96, 52W High = 101.40
Fetching data for IBTF for technical indicators...
IBTF: 50 MA = 23.28, 150 MA = 23.01, 200 MA = 22.89, 52W Low = 22.24, 52W High = 23.36
Fetching data for ATLC for technical indicators...
ATLC: 50 MA = 40.74, 150 MA = 33.70, 200 MA = 32.68, 52W Low = 23.45, 52W High = 58.73
Fetching data for TETEW for technical indicators...
Warning: Not enough data for TETEW. Skipping.
Fetching data for RGTI for technical indicators...
RGTI: 50 MA = 1.23, 150 MA = 1.08, 200 MA = 1.20, 52W Low = 0.69, 52W High = 3.05
Fetching data for INDB for technical indicators...
INDB: 50 MA = 64.69, 150 MA = 57.70, 200 MA = 55.65, 52W Low = 45.46, 52W High = 74.97
Fetching data for GP for technical indicators...
GP: 50 MA = 1.12, 150 MA = 1.14, 200 MA = 1.35, 52W Low = 0.74, 52W High = 3.33
Fetching data for TSVT for technical indicators...
TSVT: 50 MA = 4.52, 150 MA = 4.44, 200 MA = 4.59, 52W Low = 1.83, 52W High = 6.00
Fetching data for ADUR for technical indicators...
Warning: Not enough data for ADUR. Skipping.
Fetching data for PEY for technical indicators...
PEY: 50 MA = 21.86, 150 MA = 20.76, 200 MA = 20.40, 52W Low = 18.64, 52W High = 23.08
Fetching data for RFDI for technical indicators...
RFDI: 50 MA = 65.14, 150 MA = 64.55, 200 MA = 63.73, 52W Low = 56.00, 52W High = 68.14
Fetching data for HRTS for technical indicators...
HRTS: 50 MA = 33.09, 150 MA = 33.37, 200 MA = 33.27, 52W Low = 26.79, 52W High = 35.90
Fetching data for WTMAU for technical indicators...
WTMAU: 50 MA = 11.27, 150 MA = 11.15, 200 MA = 11.08, 52W Low = 10.83, 52W High = 11.44
Fetching data for TRMD for technical indicators...
TRMD: 50 MA = 27.98, 150 MA = 32.71, 200 MA = 32.09, 52W Low = 20.94, 52W High = 38.56
Fetching data for OABI for technical indicators...
OABI: 50 MA = 4.08, 150 MA = 4.26, 200 MA = 4.52, 52W Low = 3.65, 52W High = 6.69
Fetching data for WGS for technical indicators...
WGS: 50 MA = 62.90, 150 MA = 40.09, 200 MA = 32.36, 52W Low = 1.50, 52W High = 84.02
Fetching data for AFBI for technical indicators...
AFBI: 50 MA = 21.45, 150 MA = 20.61, 200 MA = 19.59, 52W Low = 14.29, 52W High = 21.93
Fetching data for TIGR for technical indicators...
TIGR: 50 MA = 6.54, 150 MA = 4.89, 200 MA = 4.61, 52W Low = 3.14, 52W High = 12.39
Fetching data for QNCX for technical indicators...
QNCX: 50 MA = 1.23, 150 MA = 0.92, 200 MA = 0.98, 52W Low = 0.54, 52W High = 2.08
Fetching data for CSB for technical indicators...
CSB: 50 MA = 59.97, 150 MA = 56.67, 200 MA = 55.75, 52W Low = 49.01, 52W High = 64.78
Fetching data for VFF for technical indicators...
VFF: 50 MA = 0.86, 150 MA = 1.02, 200 MA = 1.02, 52W Low = 0.69, 52W High = 1.53
Fetching data for NTGR for technical indicators...
NTGR: 50 MA = 21.87, 150 MA = 17.30, 200 MA = 16.70, 52W Low = 11.49, 52W High = 25.07
Fetching data for VERI for technical indicators...
VERI: 50 MA = 3.53, 150 MA = 3.15, 200 MA = 3.29, 52W Low = 1.49, 52W High = 6.97
Fetching data for ARM for technical indicators...
ARM: 50 MA = 143.10, 150 MA = 138.52, 200 MA = 135.20, 52W Low = 61.06, 52W High = 186.46
Fetching data for MDIV for technical indicators...
MDIV: 50 MA = 16.55, 150 MA = 15.97, 200 MA = 15.73, 52W Low = 14.29, 52W High = 16.94
Fetching data for SUNE for technical indicators...
SUNE: 50 MA = 4.80, 150 MA = 47.52, 200 MA = 47.71, 52W Low = 2.76, 52W High = 495.00
Fetching data for BPTH for technical indicators...
BPTH: 50 MA = 0.95, 150 MA = 1.54, 200 MA = 2.37, 52W Low = 0.75, 52W High = 11.60
Fetching data for SLNH for technical indicators...
SLNH: 50 MA = 3.55, 150 MA = 3.92, 200 MA = 3.68, 52W Low = 1.52, 52W High = 7.67
Fetching data for LPLA for technical indicators...
LPLA: 50 MA = 272.16, 150 MA = 254.98, 200 MA = 256.90, 52W Low = 192.52, 52W High = 327.35
Fetching data for PXLW for technical indicators...
PXLW: 50 MA = 0.74, 150 MA = 0.93, 200 MA = 1.30, 52W Low = 0.62, 52W High = 2.92
Fetching data for PSCE for technical indicators...
PSCE: 50 MA = 50.71, 150 MA = 51.66, 200 MA = 52.17, 52W Low = 45.97, 52W High = 57.56
Fetching data for BLRX for technical indicators...
BLRX: 50 MA = 0.46, 150 MA = 0.61, 200 MA = 0.71, 52W Low = 0.27, 52W High = 1.78
Fetching data for LBPH for technical indicators...
LBPH: 50 MA = 51.49, 150 MA = 36.11, 200 MA = 32.09, 52W Low = 3.76, 52W High = 59.98
Fetching data for WDC for technical indicators...
WDC: 50 MA = 67.01, 150 MA = 69.11, 200 MA = 68.04, 52W Low = 46.77, 52W High = 80.24
Fetching data for SBFG for technical indicators...
SBFG: 50 MA = 19.83, 150 MA = 16.45, 200 MA = 15.70, 52W Low = 12.67, 52W High = 21.79
Fetching data for WSBC for technical indicators...
WSBC: 50 MA = 32.12, 150 MA = 30.00, 200 MA = 29.44, 52W Low = 25.32, 52W High = 36.45
Fetching data for BRHY for technical indicators...
Warning: Not enough data for BRHY. Skipping.
Fetching data for BWBBP for technical indicators...
BWBBP: 50 MA = 19.64, 150 MA = 18.47, 200 MA = 18.10, 52W Low = 15.88, 52W High = 20.67
Fetching data for NXTG for technical indicators...
NXTG: 50 MA = 86.24, 150 MA = 82.94, 200 MA = 81.44, 52W Low = 71.27, 52W High = 88.68
Fetching data for AVS for technical indicators...
Warning: Not enough data for AVS. Skipping.
Fetching data for OPINL for technical indicators...
OPINL: 50 MA = 12.77, 150 MA = 11.17, 200 MA = 10.83, 52W Low = 8.96, 52W High = 14.22
Fetching data for DIOD for technical indicators...
DIOD: 50 MA = 61.90, 150 MA = 68.21, 200 MA = 68.33, 52W Low = 53.01, 52W High = 85.82
Fetching data for AVTE for technical indicators...
AVTE: 50 MA = 2.34, 150 MA = 6.08, 200 MA = 10.68, 52W Low = 1.41, 52W High = 30.75
Fetching data for HTZWW for technical indicators...
Warning: Not enough data for HTZWW. Skipping.
Fetching data for TCOM for technical indicators...
TCOM: 50 MA = 62.33, 150 MA = 52.83, 200 MA = 51.11, 52W Low = 32.76, 52W High = 68.43
Fetching data for TNXP for technical indicators...
TNXP: 50 MA = 0.15, 150 MA = 1.39, 200 MA = 3.25, 52W Low = 0.13, 52W High = 21.44
Fetching data for PLAO for technical indicators...
PLAO: 50 MA = 11.62, 150 MA = 11.52, 200 MA = 11.46, 52W Low = 11.05, 52W High = 11.65
Fetching data for ONMD for technical indicators...
ONMD: 50 MA = 0.76, 150 MA = 0.96, 200 MA = 0.91, 52W Low = 0.43, 52W High = 4.26
Fetching data for FEM for technical indicators...
FEM: 50 MA = 22.99, 150 MA = 23.23, 200 MA = 23.07, 52W Low = 20.42, 52W High = 24.75

In [59]:
# yf.pdr_override() 
# start =dt.datetime(2017,12,1)
# now = dt.datetime.now()
# final_df.DataFrame()

# for i in nasdaq_stocks.index:
#     stock=str(nasdaq_stocks["Symbol"][i])
#     #RS_Rating=nasdaq_stocks["RS Rating"][i]

#     try:
#         df = pdr.get_data_yahoo(stock, start, now)

#         smaUsed=[50,150,200]
#         for x in smaUsed:
#             sma=x
#             df["SMA_"+str(sma)]=round(df.iloc[:,4].rolling(window=sma).mean(),2)


#         currentClose=df["Adj Close"][-1]
#         moving_average_50=df["SMA_50"][-1]
#         moving_average_150=df["SMA_150"][-1]
#         moving_average_200=df["SMA_200"][-1]
#         low_of_52week=min(df["Adj Close"][-260:])
#         high_of_52week=max(df["Adj Close"][-260:])
        
#         try:
#             moving_average_200_20 = df["SMA_200"][-20]

#         except Exception:
#             moving_average_200_20=0

#         #Condition 1: Current Price > 150 SMA and > 200 SMA
#         if(currentClose>moving_average_150>moving_average_200):
#             cond_1=True
#         else:
#             cond_1=False
            
#         #Condition 2: 150 SMA and > 200 SMA
#         if(moving_average_150>moving_average_200):
#             cond_2=True
#         else:
#             cond_2=False
            
#         #Condition 3: 200 SMA trending up for at least 1 month (ideally 4-5 months)
#         if(moving_average_200>moving_average_200_20):
#             cond_3=True
#         else:
#             cond_3=False
            
#         #Condition 4: 50 SMA> 150 SMA and 50 SMA> 200 SMA
#         if(moving_average_50>moving_average_150>moving_average_200):
#             #print("Condition 4 met")
#             cond_4=True
#         else:
#             #print("Condition 4 not met")
#             cond_4=False
            
#         #Condition 5: Current Price > 50 SMA
#         if(currentClose>moving_average_50):
#             cond_5=True
#         else:
#             cond_5=False
            
#         #Condition 6: Current Price is at least 30% above 52 week low (Many of the best are up 100-300% before coming out of consolidation)
#         if(currentClose>=(1.3*low_of_52week)):
#             cond_6=True
#         else:
#             cond_6=False
            
#         #Condition 7: Current Price is within 25% of 52 week high
#         if(currentClose>=(.75*high_of_52week)):
#             cond_7=True
#         else:
#             cond_7=False
            
#         #Condition 8: IBD RS rating >70 and the higher the better
#         #if(RS_Rating>70):
#         #cond_8=True
#         #else:
#         cond_8=False

#         if(cond_1 and cond_2 and cond_3 and cond_4 and cond_5 and cond_6 and cond_7 and cond_8):
#             final_df.append({'Stock': stock, "RS_Rating": RS_Rating, "50 Day MA": moving_average_50, "150 Day Ma": moving_average_150, "200 Day MA": moving_average_200, "52 Week Low": low_of_52week, "52 week High": high_of_52week}, ignore_index=True)
# #         except Exception:
# #             print("No data on "+stock)

# # print(final_df)

In [60]:
nasdaq_stocks

    Stock     SMA_50    SMA_150    SMA_200
0    MCHI  49.747400  45.121796  43.751242
1    RFEU  64.467372  65.039977  64.590370
2     SDA   9.978200   9.223533   8.643750
3    FRSX   0.658580   0.861107   0.915800
4    BSRR  29.554496  26.175038  24.202738
..    ...        ...        ...        ...
194  TCOM  62.332000  52.830000  51.105950
195  TNXP   0.154600   1.392667   3.254100
196  PLAO  11.616000  11.520100  11.460280
197  ONMD   0.762940   0.955800   0.905180
198   FEM  22.994389  23.231262  23.065514

[199 rows x 4 columns]

In [64]:
# List to collect rows before creating the final DataFrame
rows_list = []

# Iterate over each stock in nasdaq_stocks
for i in nasdaq_stocks.index:
    stock = str(nasdaq_stocks["Stock"][i])

    try:
        print(f"Fetching data for {stock}...")
        
#         # Get 52-week low and high (assuming 260 trading days)
#         if len(df) >= 260:
#             low_of_52week = df["Adj Close"].iloc[-260:].min()
#             high_of_52week = df["Adj Close"].iloc[-260:].max()
#         else:
#             print(f"Not enough data for {stock} to calculate 52-week low/high. Skipping.")
#             continue
        moving_average_50 = nasdaq_stocks["SMA_50"][i]
        moving_average_150 = nasdaq_stocks["SMA_150"][i]
        moving_average_200 = nasdaq_stocks["SMA_200"][i]
#         # Attempt to get SMA_200 from 20 days ago
#         if len(df) >= 20:
#             moving_average_200_20 = df["SMA_200"].iloc[-20]
#         else:
#             moving_average_200_20 = 0  # Default value if not enough data

        # Define conditions
#         cond_1 = currentClose > moving_average_150 > moving_average_200
        cond_2 = moving_average_150 > moving_average_200
        #cond_3 = moving_average_200 > moving_average_200
        cond_4 = moving_average_50 > moving_average_150
#         cond_5 = currentClose > moving_average_50
#         cond_6 = currentClose >= (1.3 * low_of_52week)
#         cond_7 = currentClose >= (0.75 * high_of_52week)
#         cond_8 = RS_Rating > 70  # Ensure RS_Rating is properly defined

        # Check if all conditions are met
        #if all([cond_1, cond_2, cond_3, cond_4, cond_5, cond_6, cond_7, cond_8]):
        if all([cond_2, cond_4]):
            row = {
                'Stock': stock,
#                 'RS_Rating': RS_Rating,
                '50 Day MA': moving_average_50,
                '150 Day MA': moving_average_150,
                '200 Day MA': moving_average_200,
#                 '52 Week Low': low_of_52week,
#                 '52 week High': high_of_52week
            }
            rows_list.append(row)
            print(f"{stock} meets all conditions. Added to final_df.")
        else:
            print(f"{stock} does not meet all conditions.")

    except Exception as e:
        print(f"Error processing {stock}: {e}")

# Create the final DataFrame from the collected rows
if rows_list:
    final_df = pd.DataFrame(rows_list)
    print("\nFinal DataFrame with Stocks Meeting All Conditions:")
    print(final_df)
else:
    print("No stocks met all conditions.")

Fetching data for MCHI...
MCHI meets all conditions. Added to final_df.
Fetching data for RFEU...
RFEU does not meet all conditions.
Fetching data for SDA...
SDA meets all conditions. Added to final_df.
Fetching data for FRSX...
FRSX does not meet all conditions.
Fetching data for BSRR...
BSRR meets all conditions. Added to final_df.
Fetching data for HIVE...
HIVE does not meet all conditions.
Fetching data for FSV...
FSV meets all conditions. Added to final_df.
Fetching data for CANC...
CANC does not meet all conditions.
Fetching data for BCAN...
BCAN does not meet all conditions.
Fetching data for REYN...
REYN meets all conditions. Added to final_df.
Fetching data for JG...
JG meets all conditions. Added to final_df.
Fetching data for CMPO...
CMPO meets all conditions. Added to final_df.
Fetching data for GH...
GH does not meet all conditions.
Fetching data for UHG...
UHG does not meet all conditions.
Fetching data for CWCO...
CWCO does not meet all conditions.
Fetching data for GNSS...
GNSS meets all conditions. Added to final_df.
Fetching data for CAKE...
CAKE meets all conditions. Added to final_df.
Fetching data for MPB...
MPB meets all conditions. Added to final_df.
Fetching data for ALKS...
ALKS does not meet all conditions.
Fetching data for RZLT...
RZLT meets all conditions. Added to final_df.
Fetching data for IOSP...
IOSP does not meet all conditions.
Fetching data for MRM...
MRM does not meet all conditions.
Fetching data for TLF...
TLF does not meet all conditions.
Fetching data for AADI...
AADI does not meet all conditions.
Fetching data for CMCSA...
CMCSA does not meet all conditions.
Fetching data for LNZA...
LNZA does not meet all conditions.
Fetching data for SDSI...
SDSI meets all conditions. Added to final_df.
Fetching data for SMBC...
SMBC meets all conditions. Added to final_df.
Fetching data for ADAG...
ADAG does not meet all conditions.
Fetching data for ABCL...
ABCL does not meet all conditions.
Fetching data for VRDN...
VRDN meets all conditions. Added to final_df.
Fetching data for EGAN...
EGAN does not meet all conditions.
Fetching data for BSCO...
BSCO meets all conditions. Added to final_df.
Fetching data for CADL...
CADL does not meet all conditions.
Fetching data for WW...
WW does not meet all conditions.
Fetching data for NFLX...
NFLX meets all conditions. Added to final_df.
Fetching data for AIHS...
AIHS meets all conditions. Added to final_df.
Fetching data for VSAT...
VSAT does not meet all conditions.
Fetching data for SNEX...
SNEX meets all conditions. Added to final_df.
Fetching data for TUR...
TUR does not meet all conditions.
Fetching data for SLRC...
SLRC meets all conditions. Added to final_df.
Fetching data for EYE...
EYE does not meet all conditions.
Fetching data for LFMD...
LFMD does not meet all conditions.
Fetching data for FARO...
FARO does not meet all conditions.
Fetching data for HFWA...
HFWA meets all conditions. Added to final_df.
Fetching data for FTDR...
FTDR meets all conditions. Added to final_df.
Fetching data for UTRE...
UTRE meets all conditions. Added to final_df.
Fetching data for NERD...
NERD meets all conditions. Added to final_df.
Fetching data for CXAI...
CXAI does not meet all conditions.
Fetching data for CLMB...
CLMB meets all conditions. Added to final_df.
Fetching data for KIDS...
KIDS does not meet all conditions.
Fetching data for RDUS...
RDUS does not meet all conditions.
Fetching data for CTKB...
CTKB does not meet all conditions.
Fetching data for EJH...
EJH does not meet all conditions.
Fetching data for SOXQ...
SOXQ does not meet all conditions.
Fetching data for BNGO...
BNGO does not meet all conditions.
Fetching data for ERNA...
ERNA does not meet all conditions.
Fetching data for ICCM...
ICCM does not meet all conditions.
Fetching data for PMVP...
PMVP does not meet all conditions.
Fetching data for DRRX...
DRRX does not meet all conditions.
Fetching data for EHTH...
EHTH does not meet all conditions.
Fetching data for RILYT...
RILYT does not meet all conditions.
Fetching data for CRKN...
CRKN does not meet all conditions.
Fetching data for BCOW...
BCOW meets all conditions. Added to final_df.
Fetching data for TRUP...
TRUP meets all conditions. Added to final_df.
Fetching data for XAIR...
XAIR does not meet all conditions.
Fetching data for IEI...
IEI meets all conditions. Added to final_df.
Fetching data for SFM...
SFM meets all conditions. Added to final_df.
Fetching data for NBIX...
NBIX does not meet all conditions.
Fetching data for TURB...
TURB meets all conditions. Added to final_df.
Fetching data for TREE...
TREE meets all conditions. Added to final_df.
Fetching data for NSPR...
NSPR does not meet all conditions.
Fetching data for NATH...
NATH meets all conditions. Added to final_df.
Fetching data for VRAR...
VRAR does not meet all conditions.
Fetching data for NVX...
NVX does not meet all conditions.
Fetching data for VRTX...
VRTX meets all conditions. Added to final_df.
Fetching data for TCX...
TCX does not meet all conditions.
Fetching data for AMLI...
AMLI does not meet all conditions.
Fetching data for CLPS...
CLPS meets all conditions. Added to final_df.
Fetching data for EUDA...
EUDA meets all conditions. Added to final_df.
Fetching data for NKGN...
NKGN does not meet all conditions.
Fetching data for EWZS...
EWZS does not meet all conditions.
Fetching data for AZPN...
AZPN meets all conditions. Added to final_df.
Fetching data for AAPL...
AAPL meets all conditions. Added to final_df.
Fetching data for MNRO...
MNRO does not meet all conditions.
Fetching data for TPIC...
TPIC does not meet all conditions.
Fetching data for VYGR...
VYGR does not meet all conditions.
Fetching data for ASYS...
ASYS does not meet all conditions.
Fetching data for PNFP...
PNFP meets all conditions. Added to final_df.
Fetching data for ALGS...
ALGS does not meet all conditions.
Fetching data for ALTY...
ALTY meets all conditions. Added to final_df.
Fetching data for UBX...
UBX does not meet all conditions.
Fetching data for GLLIU...
GLLIU does not meet all conditions.
Fetching data for GOCO...
GOCO does not meet all conditions.
Fetching data for ALVO...
ALVO does not meet all conditions.
Fetching data for PPTA...
PPTA meets all conditions. Added to final_df.
Fetching data for VEON...
VEON meets all conditions. Added to final_df.
Fetching data for AZTA...
AZTA does not meet all conditions.
Fetching data for FPXI...
FPXI meets all conditions. Added to final_df.
Fetching data for SANW...
SANW does not meet all conditions.
Fetching data for HEPA...
HEPA does not meet all conditions.
Fetching data for INDP...
INDP does not meet all conditions.
Fetching data for CSPI...
CSPI does not meet all conditions.
Fetching data for ASNS...
ASNS meets all conditions. Added to final_df.
Fetching data for BANF...
BANF meets all conditions. Added to final_df.
Fetching data for CGEN...
CGEN does not meet all conditions.
Fetching data for FOLD...
FOLD does not meet all conditions.
Fetching data for RYTM...
RYTM meets all conditions. Added to final_df.
Fetching data for BULD...
BULD does not meet all conditions.
Fetching data for PY...
PY meets all conditions. Added to final_df.
Fetching data for PASG...
PASG does not meet all conditions.
Fetching data for FBOT...
FBOT meets all conditions. Added to final_df.
Fetching data for BRKL...
BRKL meets all conditions. Added to final_df.
Fetching data for TCRT...
TCRT does not meet all conditions.
Fetching data for MTRX...
MTRX does not meet all conditions.
Fetching data for SRZN...
SRZN does not meet all conditions.
Fetching data for FAST...
FAST does not meet all conditions.
Fetching data for AIMAU...
AIMAU meets all conditions. Added to final_df.
Fetching data for CDNA...
CDNA meets all conditions. Added to final_df.
Fetching data for RFIL...
RFIL meets all conditions. Added to final_df.
Fetching data for LIFWW...
LIFWW does not meet all conditions.
Fetching data for CBNK...
CBNK meets all conditions. Added to final_df.
Fetching data for NETD...
NETD meets all conditions. Added to final_df.
Fetching data for SOBR...
SOBR does not meet all conditions.
Fetching data for CFSB...
CFSB does not meet all conditions.
Fetching data for TASK...
TASK does not meet all conditions.
Fetching data for CDTX...
CDTX does not meet all conditions.
Fetching data for MLTX...
MLTX does not meet all conditions.
Fetching data for AWRE...
AWRE does not meet all conditions.
Fetching data for VBFC...
VBFC meets all conditions. Added to final_df.
Fetching data for CTXR...
CTXR does not meet all conditions.
Fetching data for IGF...
IGF meets all conditions. Added to final_df.
Fetching data for EVTV...
EVTV does not meet all conditions.
Fetching data for KRYS...
KRYS does not meet all conditions.
Fetching data for SLNO...
SLNO meets all conditions. Added to final_df.
Fetching data for AY...
AY meets all conditions. Added to final_df.
Fetching data for HBCP...
HBCP meets all conditions. Added to final_df.
Fetching data for NCNO...
NCNO meets all conditions. Added to final_df.
Fetching data for MFIC...
MFIC does not meet all conditions.
Fetching data for HOLX...
HOLX meets all conditions. Added to final_df.
Fetching data for CMND...
CMND meets all conditions. Added to final_df.
Fetching data for ENG...
ENG does not meet all conditions.
Fetching data for UMBF...
UMBF meets all conditions. Added to final_df.
Fetching data for DVLU...
DVLU meets all conditions. Added to final_df.
Fetching data for SIEB...
SIEB meets all conditions. Added to final_df.
Fetching data for XEL...
XEL meets all conditions. Added to final_df.
Fetching data for RGS...
RGS meets all conditions. Added to final_df.
Fetching data for OZKAP...
OZKAP meets all conditions. Added to final_df.
Fetching data for ALTI...
ALTI does not meet all conditions.
Fetching data for IMMR...
IMMR does not meet all conditions.
Fetching data for TTEC...
TTEC does not meet all conditions.
Fetching data for LEGH...
LEGH meets all conditions. Added to final_df.
Fetching data for NAMSW...
NAMSW does not meet all conditions.
Fetching data for OMGA...
OMGA does not meet all conditions.
Fetching data for AVDL...
AVDL does not meet all conditions.
Fetching data for KXIN...
KXIN does not meet all conditions.
Fetching data for IBTF...
IBTF meets all conditions. Added to final_df.
Fetching data for ATLC...
ATLC meets all conditions. Added to final_df.
Fetching data for RGTI...
RGTI does not meet all conditions.
Fetching data for INDB...
INDB meets all conditions. Added to final_df.
Fetching data for GP...
GP does not meet all conditions.
Fetching data for TSVT...
TSVT does not meet all conditions.
Fetching data for PEY...
PEY meets all conditions. Added to final_df.
Fetching data for RFDI...
RFDI meets all conditions. Added to final_df.
Fetching data for HRTS...
HRTS does not meet all conditions.
Fetching data for WTMAU...
WTMAU meets all conditions. Added to final_df.
Fetching data for TRMD...
TRMD does not meet all conditions.
Fetching data for OABI...
OABI does not meet all conditions.
Fetching data for WGS...
WGS meets all conditions. Added to final_df.
Fetching data for AFBI...
AFBI meets all conditions. Added to final_df.
Fetching data for TIGR...
TIGR meets all conditions. Added to final_df.
Fetching data for QNCX...
QNCX does not meet all conditions.
Fetching data for CSB...
CSB meets all conditions. Added to final_df.
Fetching data for VFF...
VFF does not meet all conditions.
Fetching data for NTGR...
NTGR meets all conditions. Added to final_df.
Fetching data for VERI...
VERI does not meet all conditions.
Fetching data for ARM...
ARM meets all conditions. Added to final_df.
Fetching data for MDIV...
MDIV meets all conditions. Added to final_df.
Fetching data for SUNE...
SUNE does not meet all conditions.
Fetching data for BPTH...
BPTH does not meet all conditions.
Fetching data for SLNH...
SLNH does not meet all conditions.
Fetching data for LPLA...
LPLA does not meet all conditions.
Fetching data for PXLW...
PXLW does not meet all conditions.
Fetching data for PSCE...
PSCE does not meet all conditions.
Fetching data for BLRX...
BLRX does not meet all conditions.
Fetching data for LBPH...
LBPH meets all conditions. Added to final_df.
Fetching data for WDC...
WDC does not meet all conditions.
Fetching data for SBFG...
SBFG meets all conditions. Added to final_df.
Fetching data for WSBC...
WSBC meets all conditions. Added to final_df.
Fetching data for BWBBP...
BWBBP meets all conditions. Added to final_df.
Fetching data for NXTG...
NXTG meets all conditions. Added to final_df.
Fetching data for OPINL...
OPINL meets all conditions. Added to final_df.
Fetching data for DIOD...
DIOD does not meet all conditions.
Fetching data for AVTE...
AVTE does not meet all conditions.
Fetching data for TCOM...
TCOM meets all conditions. Added to final_df.
Fetching data for TNXP...
TNXP does not meet all conditions.
Fetching data for PLAO...
PLAO meets all conditions. Added to final_df.
Fetching data for ONMD...
ONMD does not meet all conditions.
Fetching data for FEM...
FEM does not meet all conditions.

Final DataFrame with Stocks Meeting All Conditions:
    Stock   50 Day MA  150 Day MA  200 Day MA
0    MCHI   49.747400   45.121796   43.751242
1     SDA    9.978200    9.223533    8.643750
2    BSRR   29.554496   26.175038   24.202738
3     FSV  186.016313  169.457412  167.334401
4    REYN   28.864341   28.693898   28.525766
..    ...         ...         ...         ...
83  BWBBP   19.640148   18.472234   18.095339
84   NXTG   86.236236   82.944483   81.435611
85  OPINL   12.767989   11.166599   10.825397
86   TCOM   62.332000   52.830000   51.105950
87   PLAO   11.616000   11.520100   11.460280

[88 rows x 4 columns]

In [65]:
print(final_df)

    Stock   50 Day MA  150 Day MA  200 Day MA
0    MCHI   49.747400   45.121796   43.751242
1     SDA    9.978200    9.223533    8.643750
2    BSRR   29.554496   26.175038   24.202738
3     FSV  186.016313  169.457412  167.334401
4    REYN   28.864341   28.693898   28.525766
..    ...         ...         ...         ...
83  BWBBP   19.640148   18.472234   18.095339
84   NXTG   86.236236   82.944483   81.435611
85  OPINL   12.767989   11.166599   10.825397
86   TCOM   62.332000   52.830000   51.105950
87   PLAO   11.616000   11.520100   11.460280

[88 rows x 4 columns]